version: "3.5"
services:
  nats:
    image: nats:alpine
    container_name: nats
    restart: always
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port